#测试异常
try:
    test = 6/0
except Exception as e:
    print(e)